require_relative '../lib/basic/version'

def create_manifest
  title =  'Implementation-Title: jruby-ext (example JRuby Extension)'        
  version =  format('Implementation-Version: %s', BasicExample::VERSION)
  file = File.open('MANIFEST.MF', 'w') do |f|
    f.puts(title)
    f.puts(version)
  end
end

task default: [:init, :compile]

desc 'Create Manifest'
task :init do
  create_manifest
end

desc 'Compile'
task :compile do
  sh 'mvn package'
  sh 'mv target/jruby-ext.jar ../lib'
end

desc 'clean'
task :clean do
  Dir['./**/*.%w{jar}'].each do |path|
    puts 'Deleting #{path} ...'
    File.delete(path)
  end
  FileUtils.rm_rf('./target')
end
